flowchart LR
    %% Sources:
    subgraph source["1\. Original sources"]
        subgraph src1["src/ (content)"]
            srcIndex["index/<br>├── module/(<i class='fa-brands fa-square-js' style='color: #f7e025'></i><i class='fa-brands fa-sass' style='color: #ce6b9c'></i><i class='fa-regular fa-file-powerpoint' style='color: #e54c21'></i>) <br>└── template.html <i class='fa-brands fa-html5' style='color: #e54c21'></i>"]:::boxSource
            srcPages["pages/<br>├── page1/<br>│ ├── module/(<i class='fa-brands fa-square-js' style='color: #f7e025'></i><i class='fa-brands fa-sass' style='color: #ce6b9c'></i><i class='fa-regular fa-file-powerpoint' style='color: #e54c21'></i>)<br>│ └── template.html<i class='fa-brands fa-html5' style='color: #e54c21'></i><br>└── ..."]:::boxSource
            srcBlog["blog/<br>├── module/(<i class='fa-brands fa-square-js' style='color: #f7e025'></i><i class='fa-brands fa-sass' style='color: #ce6b9c'></i><i class='fa-regular fa-file-powerpoint' style='color: #e54c21'></i>)<br>├── template.html <i class='fa-brands fa-html5' style='color: #e54c21'></i><br>├── post1.qmd <i class='fa-brands fa-markdown' style='color: #447da4'></i><br>└── ..."]:::boxSource
        end

        subgraph src2["src/ (assets)"]
            srcGlobal["global/(<i class='fa-brands fa-square-js' style='color: #f7e025'></i><i class='fa-brands fa-sass' style='color: #ce6b9c'></i><i class='fa-regular fa-file-powerpoint' style='color: #e54c21'></i>)"]:::boxSource
        end

        subgraph projs["External sources"]
            proj1["proj1/<br>└── docs/(<i class='fa-brands fa-html5' style='color: #e54c21'></i><i class='fa-brands fa-square-js' style='color: #f7e025'></i><i class='fa-brands fa-css3-alt' style='color: #306af1'></i>)"]:::boxSource
            projN["projN/<br>└── ..."]:::boxSource
        end

        subgraph static["static/"]
            staticStatic["404.html, ...<br>img/ ..."]:::boxSource
        end
    end

    %% Build system:
    subgraph build["2\. Build system"]
        buildConfigs["Orchestration:<br>config/sources.yml<br>dev/dev.py<br>.github/build.yml"]:::boxSource
        buildAssets["Assets"]:::boxBuild
        buildBlog["Blog"]:::boxBuild
        buildPages["Pages"]:::boxBuild
        buildProj["Projects"]:::boxBuild
    end

    %% Final site:
    subgraph site["3\. Site"]
        siteAssets["assets/<br>├── img/<br>├── (<i class='fa-brands fa-square-js' style='color: #f7e025'></i><i class='fa-brands fa-css3-alt' style='color: #306af1'></i>)<br>└── ..."]:::boxSite
        siteMeta["404.html, ..."]:::boxSource
        siteBlog["blog/<br>├── index.html <i class='fa-brands fa-html5' style='color: #e54c21'></i><br>├── post1.html <i class='fa-brands fa-html5' style='color: #e54c21'></i><br>└── ..."]:::boxSite
        sitePage1["page1/<br>├── index.html <i class='fa-brands fa-html5' style='color: #e54c21'></i><br>└── ..."]:::boxSite
        sitePageN["pageN/<br>└── ..."]:::boxSite
        siteIndex["index.html <i class='fa-brands fa-html5' style='color: #e54c21'></i>"]:::boxSite
        siteGroup1["group1/<br>├── proj1/(<i class='fa-brands fa-html5' style='color: #e54c21'></i><i class='fa-brands fa-square-js' style='color: #f7e025'></i><i class='fa-brands fa-css3-alt' style='color: #306af1'></i>)<br>├── proj3/(<i class='fa-brands fa-html5' style='color: #e54c21'></i><i class='fa-brands fa-square-js' style='color: #f7e025'></i><i class='fa-brands fa-css3-alt' style='color: #306af1'></i>)<br>└── ..."]:::boxSite
        siteGroupN["groupN/<br>└── ..."]:::boxSite
    end

    %% Lines to builder:
    srcIndex --> buildPages
    srcPages --> buildPages
    srcGlobal -.-> buildPages

    srcBlog --> buildBlog
    srcGlobal -.-> buildBlog

    proj1 --> buildProj
    projN --> buildProj

    srcGlobal -.-> buildAssets
    staticStatic -.-> buildAssets

    %% HTML flows
    pagesAgg[" "]
    buildPages --- pagesAgg
    pagesAgg --> siteIndex
    pagesAgg --> sitePage1
    pagesAgg --> sitePageN

    buildBlog --> siteBlog

    buildProj --> siteGroup1
    buildProj --> siteGroupN

    %% Assets flow
    buildPages -.-> siteAssets
    buildBlog -.-> siteAssets

    buildAssets -.-> siteMeta
    buildAssets -.-> siteAssets
    
    %% Styling
    class source,static,src1,src2,projs boxSource;
    class build boxBuild;
    class site boxSite;
    class pagesAgg tinyBox;

    classDef tinyBox fill:#00000000,stroke:#00000000,stroke-width:0.5,color:#00000000,font-size:1px,height:1px,width:1px;
    classDef boxSource fill:#008c99,stroke:#444444,stroke-width:2,color:#ffffff,stroke-dasharray:0,text-align:left,font-family:monospace;
    classDef boxBuild fill:#cc5500,stroke:#444444,stroke-width:2,color:#ffffff,stroke-dasharray:0,text-align:left,font-family:monospace;
    classDef boxSite fill:#00805b,stroke:#444444,stroke-width:2,color:#ffffff,stroke-dasharray:0,text-align:left,font-family:monospace;